version: "3"
services:
  admin-db:
    image: postgres:16
    container_name: admin-db
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
